Don't TEMP_FAILURE_RETRY calls that can't fail.
It turns out that while GCC doesn't care, clang is unhappy with us
because it notices that we're comparing an unsigned value (like a uid_t)
against -1:

  libcore/luni/src/main/native/libcore_io_Posix.cpp:727:12: error: comparison
  of integers of different signs: 'typeof (getegid())' (aka 'unsigned int')
  and 'int' [-Werror,-Wsign-compare]
    return TEMP_FAILURE_RETRY(getegid());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bug: 18759467
Change-Id: If71b11cbdd0cda2b8efcc1706eb49856c3770bb8
Signed-off-by: Chet Kener <Cl3Kener@gmail.com>